name: pipeline-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test || echo "No tests yet"

      - name: Start app (smoke check)
        run: |
          node src/app.js &
          sleep 5
          echo "App started successfully"

        # Maestro tests (add them later)
