appId: host.exp.exponent
---
# Test: exercise the POI panel and directions

- tapOn:
    id: poiPress

- waitForAnimationToEnd

- tapOn: "gps"

- tapOn:
    text: "Only this time"
    optional: true

- waitForAnimationToEnd    

- tapOn: Load

# 87% is the height, 40% can be changed for different distances
- tapOn:
    point: 60%,87%

- tapOn: Load

- tapOn:
    point: 40%,87%

- tapOn: Load

- waitForAnimationToEnd

- tapOn:
    id: "poi-.*"

- tapOn: "Get Directions"

- assertVisible: "Plan Your Trip"