appId: host.exp.exponent
---
# Test: exercise the POI panel and directions

- tapOn:
    id: poiPress

- waitForAnimationToEnd    

# adjusting place for specific tapping
- tapOn: SGW
- waitForAnimationToEnd    
- tapOn: Loyola
- waitForAnimationToEnd    

# looking for JMSB -> CL
- tapOn:
    point: 30%,68%

- tapOn: Load

# 87% is the height, 40% can be changed for different distances
# loading multiple times to guarantee the starbucks pops out
- tapOn:
    point: 60%,87%

- tapOn: Load

- tapOn:
    point: 40%,87%

- tapOn: Load

- tapOn:
    point: 20%,87%

- tapOn: Load

- waitForAnimationToEnd

- tapOn:
    point: 45%,46%

- tapOn: "Get Directions"

- assertVisible: "Plan Your Trip"