import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  mapWrap: {
    height: 260,
    marginHorizontal: 16,
    borderRadius: 16,
    overflow: "hidden",
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#eee",
  },
  routeContainerSelected: {
    borderWidth: 3,
    borderColor: "#7C2B38",
    backgroundColor: "#7C2B38",
  },
  routeTextSelected: {
    color: "#fff",
  },
  routeSubTextSelected: {
    color: "rgba(255,255,255,0.8)",
  },
  background: {
    flex: 1,
    overflow: "hidden",
  },
  backgroundImage: {
    width: "100%",
  },
  header: {
    width: "100%",
    paddingTop: 35,
    paddingHorizontal: 20,
    position: "relative",
    zIndex: 10,
  },
  backBtn: {
    position: "absolute",
    top: 30,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    color: "white",
    fontSize: 28,
    fontWeight: "700",
    marginTop: 30,
  },
  headerSubtitle: {
    color: "rgba(255,255,255,0.8)",
    marginTop: 6,
    marginBottom: 6,
    fontSize: 13,
  },
  input: {
    borderWidth: 1,
    borderColor: "white",
    borderRadius: 14,
    padding: 10,
    marginTop: 14,
    backgroundColor: "white",
  },
  inputLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 4,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  inputField: {
    flex: 1,
    fontSize: 16,
    color: "#111",
    paddingVertical: 4,
  },
  dropdown: {
    maxHeight: 200,
    borderTopWidth: 1,
    borderTopColor: "#eee",
    marginTop: 6,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#eee",
  },
  dropdownText: {
    fontSize: 14,
    color: "#333",
    flex: 1,
  },
  loadingRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
  },
  loadingText: {
    fontSize: 14,
    color: "#666",
  },
  errorText: {
    fontSize: 14,
    color: "#c00",
    padding: 16,
  },
  errorContainer: {
    marginTop: 20,
    padding: 16,
    backgroundColor: "white",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomPart: {
    flex: 1,
    marginTop: 40,
    paddingHorizontal: 16,
    backgroundColor: "white",
    paddingTop: 10,
    overflow: "hidden",
  },
  liveLoc: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 14,
    padding: 10,
    marginBottom: 10,
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  routesHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  routesTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111",
  },
  filterText: {
    color: "#7C2B38",
    fontWeight: "800",
  },
  routesContent: {},
  routeContainer: {
    backgroundColor: "white",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#7C2B38",
    flexDirection: "row",
    marginBottom: 16,
    marginHorizontal: 16,
    height: 170,
  },
  routeBody: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
  },
  routeIcon: { marginRight: 14 },
  routeDetails: { flex: 1 },
  routeMode: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111",
    marginBottom: 4,
  },
  routeTime: {
    fontSize: 16,
    color: "#333",
    marginBottom: 2,
  },
  routeDistance: {
    fontSize: 13,
    color: "#666",
  },
  routeSchedule: {
    fontSize: 12,
    color: "#7C2B38",
    marginTop: 4,
    fontStyle: "italic",
  },
  emptyStateContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyStateTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    marginBottom: 6,
  },
  emptyStateText: {
    fontSize: 14,
    color: "#777",
    textAlign: "center",
  },
  retryButton: {
    marginTop: 20,
    backgroundColor: "#912338",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 6,
  },
  retryButtonText: {
    color: "white",
    fontWeight: "600",
  },
});